apiVersion: v1
kind: Pod
metadata:
  name: validador-jenkins
  labels:
    app: validador-jenkins
spec:
  containers:
    - name: container-validador-jenkins
      image: didox/ilab-java-tdd
      ports:
        - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: nodeport-validador-jenkins
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30000
  selector:
    app: validador-jenkins
